# Generated by Django 6.1.1 on 2026-09-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
