# Generated by Django 6.1.1 on 2026-09-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_questcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questcompletion',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_history', to='quests.quest'),
        ),
    ]
